version: '1'

services:
  manager: 
    build: 
      context: ./hashCrackManager
    environment : 
      WORKERS_AMOUNT: 4
      WORKERS_URL: worker1:8080,worker2:8080,worker3:8080,worker4:8080
    ports:
      - "8080:8080"
    container_name: manager


  worker1: 
    build:
      context: ./hashCrackWorker
    ports:
      - "8081:8080"
    container_name: worker1


  worker2: 
    build:
      context: ./hashCrackWorker
    ports:
      - "8082:8080"
    container_name: worker2

  worker3: 
    build:
      context: ./hashCrackWorker
    ports:
      - "8083:8080"
    container_name: worker3


  worker4: 
    build:
      context: ./hashCrackWorker
    ports:
      - "8084:8080"
    container_name: worker4
